services:
  web:
    build: .
    container_name: django_web_container
    ports:
      - "8000:8000"
    volumes:
      - .:/report_generator
    environment:
      DEBUG: True
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: report_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
